### ISSUE TITLE
Can you provide a demo?

### ISSUE THREAD

**Issue by DaxChen** [patrickml/react-modal#1]
Can you make a simple demo so we can see the effect without downloading it and try it out by ourselves?

**Comment by patrickml** [comment]
@YuHuaiChen Yup I can do that

**Comment by patrickml** [comment]
@YuHuaiChen here is the demo http://react-modal.meteor.com/

**Comment by DaxChen** [comment]
Thanks!
Looks really nice!

**Comment by patrickml** [comment]
Thanks!
