### ISSUE TITLE
What is a good approach to close the modal? i.e. when a button in it was clicked.

### ISSUE THREAD

**Issue by alekkowalczyk** [patrickml/react-modal#2]
I made it this way:
`$(".md-close").trigger("click");`
I guess not the most elegant way :)

**Comment by patrickml** [comment]
@alekkowalczyk I actually need to push out a major update for this because i have removed everything to do with jQuery to keep everything stateful. I will keep you posted. Il try to do the release tonight.

With the new way I have planned you import the ModalMixin which will give your component `openModal` and `closeModal` so you can control it at will. The only downside is you will only be able to have one modal rendered within a template.

**Comment by alekkowalczyk** [comment]
Hmm... the issue with one modal within a template could be really big and lead to artifical splitting the code into seperate react components. I dunno if that's a good approach. But besides that, it works nice now for me :)

**Comment by patrickml** [comment]
Yeh I'm more concerned with the fact that currently it's using jquery to
open and close the modal which means the Dom isn't in sync with the virtual
Dom and worst case senecio with one modal per component you would just have
to create a component for your modal like SignupModal which contains all of
the logic for that modal. Il post a better example later.

**Comment by alekkowalczyk** [comment]
Ok, that sounds good, providing a pattern with an example that for each modal a react component has to be created. (if it's not a "hello world" scenario with one modal)

**Comment by patrickml** [comment]
@alekkowalczyk I just pushed out the changed with updated docs and a demo which can be found here https://github.com/patrickml/react-modal

**Comment by patrickml** [comment]
@alekkowalczyk let me know if you have any issues using the modal

**Comment by alekkowalczyk** [comment]
I have, I refactorred it using the "controlled modal" approach, exactly as in the demo - but when I click the button to show it up (change the state of the parent), only the opacity background appears, the modal itself has visibility:hidden.

**Comment by alekkowalczyk** [comment]
It started to work properly when I mixed it with the earlier approach, that is - give the modal an id, and add the data-modal attribute to the button which opens the modal.

**Comment by patrickml** [comment]
@alekkowalczyk thats interesting can you upload a demo of it not working? because the data-modal doesnt exist anymore. R u sure you updated the package in your application?

**Comment by alekkowalczyk** [comment]
ok I see, I have versoin 1.0.1 and your changes are in 2.0.0 - but `meteor add patrickml:react-modal` adds a reference to 1.0.1, could you update the version on atmospherejs?

**Comment by patrickml** [comment]
Oh wow yeh it should have been updated I will update it now. Sorry about that

**Comment by patrickml** [comment]
It should be up now

**Comment by alekkowalczyk** [comment]
Yup, now it works - thanks! :-)
