### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by Hamatek** [patrickml/react-modal#3]
Hello , nice tinny modal package it would be awesome if we could use custom css and easily remove/replace default one maybe with some options like : 

`let options = {
defaultCss= false,
headerCss ='my-css',
closeBtnCss ='my-css',
}`

thanks again for your package ~

Cheers

**Comment by patrickml** [comment]
@Hamatek yeh i agree it would be nice to be able to add custom classes easily like that. The next time im working on the package I will add that in.

For now you can add `.md-modal` `.md-content` and `.md-body` to your stylesheets and overwrite the styling. But i will add the ability to add multiple custom classes.

**Comment by patrickml** [comment]
@Hamatek are you looking for something like this as well?

``` jsx
ConfirmModal = React.createClass({
  mixins : [ReactModalMixin],
  handleClick () {
    this.props.onClick(this.closeModal);
  },
  render () {
    let instance = this;
    return (
      <span>
        <button
          onClick={ instance.openModal }
          className="button">
          { instance.props.buttonText }
        </button>
        <Modal
          isOpen={ instance.state.isOpen }
          close={ instance.closeModal }
          title={ instance.props.title }
          options={{
            style : {
              maxWidth : '300px'
            }
          }}
          >
          <div className="md-footer">
            <button className="button" onClick={ instance.closeModal }>Cancel</button>
            <button className="button" onClick={ instance.handleClick }>{ instance.props.confirmButton || 'Create' }</button>
          </div>
        </Modal>
      </span>
    );
  }
});
```

**Comment by Hamatek** [comment]
@patrickml hmm not exactly, what happened when i tried your package is that your css is overriding my app css. it would be nice to have just the animation css as a static one if it's required, and have the rest like md-footer/md-content not hard coded.

so by passing options to a modal you can use the default css or replace it with custom css so your md-footer would look like sth like that (with classNames package):

``` javascript
 <div className=classNames({'md-footer': this.props.options.defaultCss, this.props.options.footerCss })>
            <button className="button" onClick={ instance.closeModal }>Cancel</button>
            <button className="button" onClick={ instance.handleClick }>{ instance.props.confirmButton || 'Create' }</button>
          </div>
```

well that's my 2cents

cheers

**Comment by patrickml** [comment]
ahhh gotcha. The only thing is if i replace the classes then you will lose the opening and closing of the modal. What i can do is make a way to add on additional classes. For now have you tried to use the `id` prop so that your app can beat the packages css?

`#modal-one .md-modal .md-body {}`

**Comment by Hamatek** [comment]
maybe you could split the class that open and close and animate the modal and the one that style the modal like you would do if you were having different modal theme.

I know that even as it is could override the css with my own making use if the id or of !important but imo it would be a cleaner approach to just be able to input my own css and disable the current styling/theme ~

**Comment by patrickml** [comment]
Okay great point. I just got done working out the themeing system. Basicly you will pass `theme="something-theme"` as a prop and it will add the class to the modal and if you do not have the `theme` prop then it will add the `default-theme` class

**Comment by patrickml** [comment]
you can then style everything using 

`.new-theme .md-modal .md-body` with no conflicts

**Comment by patrickml** [comment]
@Hamatek https://github.com/patrickml/react-modal#theming

**Comment by Hamatek** [comment]
@patrickml  hey looks nice thank you for your quick update I'll try it out, but is there is a reason you left the `font-family: Helvetica Neue;` on `md-modal` ?

**Comment by patrickml** [comment]
Nope totally missed that one. https://github.com/patrickml/react-modal/issues/4

Sorry about that. Thanks for pointing that out.
